# Creating master dataframe

# Libaries

In [1]:
import pandas as pd

In [94]:
df = pd.read_csv('mypersonality_cleaned.csv')
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)

In [95]:
df.drop(['#AUTHID','sentiNEG','sentiPOS','sentiNEU','sentiCOMPOUND','DATE',
         'NETWORKSIZE','BETWEENNESS','NBETWEENNESS','DENSITY',
         'BROKERAGE','NBROKERAGE','TRANSITIVITY','cEXT','cNEU','cAGR','cCON','cOPN'],axis=1, inplace=True)

In [96]:
df

,STATUS,sEXT,sNEU,sAGR,sCON,sOPN
0,likes the sound of thunder.,2.65,3.00,3.15,3.25,4.40
1,is so sleepy it's not even funny that's she ca...,2.65,3.00,3.15,3.25,4.40
2,is sore and wants the knot of muscles at the b...,2.65,3.00,3.15,3.25,4.40
3,likes how the day sounds in this new song.,2.65,3.00,3.15,3.25,4.40
4,is home. <3,2.65,3.00,3.15,3.25,4.40
...,...,...,...,...,...,...
9912,little things give you away.,2.15,2.15,4.10,2.90,4.60
9913,is wishing it was Saturday.,4.05,3.35,3.80,3.95,4.50
9914,is studying hard for the G.R.E.,4.05,3.35,3.80,3.95,4.50
9915,snipers get more head,1.40,4.05,3.30,3.40,3.95
9916,Last night was amazing! Not only did I see *PR...,4.25,3.00,3.25,3.50,4.00

In [97]:
df.rename(columns={'sEXT': "Extraversion", 'sNEU': "Neuroticism", 'sAGR':"Agreeablenes",
                   'sCON':"Consciousness" ,'sOPN':"Openness",'STATUS':"status_update"},inplace=True)

In [98]:
df = df.reindex(['status_update','Openness','Consciousness','Extraversion','Agreeablenes','Neuroticism'], axis=1)

In [99]:
df

,status_update,Openness,Consciousness,Extraversion,Agreeablenes,Neuroticism
0,likes the sound of thunder.,4.40,3.25,2.65,3.15,3.00
1,is so sleepy it's not even funny that's she ca...,4.40,3.25,2.65,3.15,3.00
2,is sore and wants the knot of muscles at the b...,4.40,3.25,2.65,3.15,3.00
3,likes how the day sounds in this new song.,4.40,3.25,2.65,3.15,3.00
4,is home. <3,4.40,3.25,2.65,3.15,3.00
...,...,...,...,...,...,...
9912,little things give you away.,4.60,2.90,2.15,4.10,2.15
9913,is wishing it was Saturday.,4.50,3.95,4.05,3.80,3.35
9914,is studying hard for the G.R.E.,4.50,3.95,4.05,3.80,3.35
9915,snipers get more head,3.95,3.40,1.40,3.30,4.05
9916,Last night was amazing! Not only did I see *PR...,4.00,3.50,4.25,3.25,3.00

In [100]:
df2 = pd.read_csv('final_df.csv')

In [101]:
df2.drop('userid',axis=1, inplace=True)

In [102]:
df2.rename(columns={'sEXT': "Extraversion", 'sNEU': "Neuroticism", 
                   'sAGR':"Agreeablenes",'sCON':"Consciousness" ,'sOPN':"Openness"},inplace=True)

In [103]:
df2

,status_update,Openness,Consciousness,Extraversion,Agreeablenes,Neuroticism
0,I am in fact that which you would call a rappe...,5.0,2.75,4.0,3.75,2.50
1,Truly there aint no rest for the wicked,5.0,2.75,4.0,3.75,2.50
2,Just another night of the tree and I,5.0,2.75,4.0,3.75,2.50
3,"Since I got to college, I've become a master a...",5.0,2.75,4.0,3.75,2.50
4,Rich are poor sunny days are still sunny,5.0,2.75,4.0,3.75,2.50
...,...,...,...,...,...,...
560232,can't wait until next sunday! <3,3.0,4.00,4.0,4.50,1.25
560233,babysitting :),3.0,4.00,4.0,4.50,1.25
560234,"Dear COD,\r\ni hate you. You consistantly stea...",3.0,4.00,4.0,4.50,1.25
560235,is in an amazing mood for some unknown reason XD,3.0,4.00,4.0,4.50,1.25
560236,is trying to not cry... its impossible tho.,3.0,4.00,4.0,4.50,1.25

In [107]:
master_df = pd.concat([df, df2],ignore_index=True)
master_df

,status_update,Openness,Consciousness,Extraversion,Agreeablenes,Neuroticism
0,likes the sound of thunder.,4.4,3.25,2.65,3.15,3.00
1,is so sleepy it's not even funny that's she ca...,4.4,3.25,2.65,3.15,3.00
2,is sore and wants the knot of muscles at the b...,4.4,3.25,2.65,3.15,3.00
3,likes how the day sounds in this new song.,4.4,3.25,2.65,3.15,3.00
4,is home. <3,4.4,3.25,2.65,3.15,3.00
...,...,...,...,...,...,...
570149,can't wait until next sunday! <3,3.0,4.00,4.00,4.50,1.25
570150,babysitting :),3.0,4.00,4.00,4.50,1.25
570151,"Dear COD,\r\ni hate you. You consistantly stea...",3.0,4.00,4.00,4.50,1.25
570152,is in an amazing mood for some unknown reason XD,3.0,4.00,4.00,4.50,1.25
570153,is trying to not cry... its impossible tho.,3.0,4.00,4.00,4.50,1.25

In [108]:
master_df.to_csv('master_data.csv')